# Generated by Django 6.0.2 on 2026-02-10 14:20

import detection.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('detected_count', models.IntegerField(default=0)),
                ('compliant_count', models.IntegerField(default=0)),
                ('non_compliant_count', models.IntegerField(default=0)),
                ('detections', models.JSONField(default=list)),
                ('image_path', models.CharField(blank=True, max_length=500, null=True)),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Detection Records',
                'db_table': 'detection_records',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='detection_r_timesta_fd6b6c_idx'), models.Index(fields=['session_id'], name='detection_r_session_6d6f53_idx')],
            },
        ),
        migrations.CreateModel(
            name='DetectionSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('error', 'Error')], default='active', max_length=20)),
                ('total_frames', models.IntegerField(default=0)),
                ('total_detections', models.IntegerField(default=0)),
                ('total_violations', models.IntegerField(default=0)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('camera_id', models.CharField(blank=True, max_length=100, null=True)),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detection_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Detection Sessions',
                'db_table': 'detection_sessions',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='ViolationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violation_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('worker_id', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('worker_name', models.CharField(blank=True, max_length=200, null=True)),
                ('missing_ppe', models.JSONField(default=list, help_text='List of missing PPE types')),
                ('detected_ppe', models.JSONField(default=list, help_text='List of detected PPE types')),
                ('image', models.ImageField(upload_to=detection.models.violation_image_upload_path)),
                ('bounding_box', models.JSONField(help_text='Bounding box coordinates')),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('reviewed', 'Reviewed'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='open', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('alert_sent', models.BooleanField(default=False)),
                ('alert_sent_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_violations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Violation Records',
                'db_table': 'violation_records',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='violation_r_timesta_e30513_idx'), models.Index(fields=['worker_id'], name='violation_r_worker__a2221e_idx'), models.Index(fields=['status'], name='violation_r_status_08c53f_idx'), models.Index(fields=['severity'], name='violation_r_severit_4078d4_idx')],
            },
        ),
    ]
