# Generated by Django 4.2.17 on 2026-02-17 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0002_worker_face_fields'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('supervisor', 'Supervisor'), ('operator', 'Operator'), ('viewer', 'Viewer'), ('worker', 'Worker')], default='viewer', max_length=20),
        ),
        migrations.CreateModel(
            name='WorkerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fcm_token', models.TextField(blank=True, null=True)),
                ('device_id', models.CharField(blank=True, max_length=200, null=True)),
                ('enable_notifications', models.BooleanField(default=True)),
                ('notify_on_violation', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='worker_account', to=settings.AUTH_USER_MODEL)),
                ('worker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_account', to='workers.worker')),
            ],
            options={
                'verbose_name_plural': 'Worker Accounts',
                'db_table': 'worker_accounts',
            },
        ),
    ]
