# Generated by Django 6.0.2 on 2026-02-10 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('alert_type', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Push Notification'), ('webhook', 'Webhook')], max_length=20)),
                ('destination', models.CharField(help_text='Email address, phone number, webhook URL, etc.', max_length=500)),
                ('min_severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('violation_threshold', models.IntegerField(default=1, help_text='Number of violations before triggering alert')),
                ('time_window_minutes', models.IntegerField(default=60, help_text='Time window in which to count violations')),
                ('is_active', models.BooleanField(default=True)),
                ('department_filter', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Alert Configurations',
                'db_table': 'alert_configs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AlertHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('alert_type', models.CharField(max_length=20)),
                ('destination', models.CharField(max_length=500)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('severity', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('retrying', 'Retrying')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Alert History',
                'db_table': 'alert_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(choices=[('supervisor', 'Supervisor'), ('manager', 'Manager'), ('safety_officer', 'Safety Officer'), ('admin', 'Administrator')], max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('receive_email_alerts', models.BooleanField(default=True)),
                ('receive_sms_alerts', models.BooleanField(default=False)),
                ('receive_push_alerts', models.BooleanField(default=False)),
                ('min_severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='high', max_length=20)),
                ('department_filter', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Alert Recipients',
                'db_table': 'alert_recipients',
                'ordering': ['name'],
            },
        ),
    ]
