# Generated by Django 6.0.2 on 2026-02-10 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alerts', '0001_initial'),
        ('detection', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alertconfig',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_alert_configs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alerthistory',
            name='config',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='alerts.alertconfig'),
        ),
        migrations.AddField(
            model_name='alerthistory',
            name='triggered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alerthistory',
            name='violation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='detection.violationrecord'),
        ),
        migrations.AddIndex(
            model_name='alerthistory',
            index=models.Index(fields=['-created_at'], name='alert_histo_created_854e93_idx'),
        ),
        migrations.AddIndex(
            model_name='alerthistory',
            index=models.Index(fields=['status'], name='alert_histo_status_7b6c20_idx'),
        ),
        migrations.AddIndex(
            model_name='alerthistory',
            index=models.Index(fields=['severity'], name='alert_histo_severit_c58dcb_idx'),
        ),
    ]
