# Generated by Django 6.0.2 on 2026-02-10 14:20

import django.db.models.deletion
import workers.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_id', models.CharField(db_index=True, help_text='Unique worker identifier', max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('department', models.CharField(blank=True, choices=[('construction', 'Construction'), ('manufacturing', 'Manufacturing'), ('maintenance', 'Maintenance'), ('warehouse', 'Warehouse'), ('laboratory', 'Laboratory'), ('cleaning', 'Cleaning'), ('other', 'Other')], max_length=50, null=True)),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
                ('shift', models.CharField(choices=[('day', 'Day Shift'), ('night', 'Night Shift'), ('rotating', 'Rotating Shift'), ('flexible', 'Flexible')], default='day', max_length=20)),
                ('photo', models.ImageField(blank=True, help_text='Worker photo for identification', null=True, upload_to=workers.models.worker_photo_upload_path)),
                ('required_ppe', models.JSONField(blank=True, default=list, help_text='List of required PPE types for this worker')),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('employee_id', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_workers', to=settings.AUTH_USER_MODEL)),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='workers.worker')),
            ],
            options={
                'verbose_name_plural': 'Workers',
                'db_table': 'workers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkerShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('shift_type', models.CharField(choices=[('day', 'Day Shift'), ('night', 'Night Shift'), ('rotating', 'Rotating Shift'), ('flexible', 'Flexible')], max_length=20)),
                ('check_in', models.TimeField(blank=True, null=True)),
                ('check_out', models.TimeField(blank=True, null=True)),
                ('violations_count', models.IntegerField(default=0)),
                ('alerts_triggered', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='workers.worker')),
            ],
            options={
                'verbose_name_plural': 'Worker Shifts',
                'db_table': 'worker_shifts',
                'ordering': ['-date', 'shift_type'],
            },
        ),
        migrations.AddIndex(
            model_name='worker',
            index=models.Index(fields=['worker_id'], name='workers_worker__4f7f05_idx'),
        ),
        migrations.AddIndex(
            model_name='worker',
            index=models.Index(fields=['department'], name='workers_departm_f58789_idx'),
        ),
        migrations.AddIndex(
            model_name='worker',
            index=models.Index(fields=['is_active'], name='workers_is_acti_e9f21c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workershift',
            unique_together={('worker', 'date', 'shift_type')},
        ),
    ]
